version: "3.9"
   
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=heka_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  django:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=heka_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234


