name: Docker Deploy Production

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  Backend-Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: docker build --tag deneme:v1 ..
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        local-image: deneme:v1
        image: deneme:v1, deneme:latest
        
  EC2-Deployment:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: [Backend-Build]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: ${{ secrets.EC2_PORT }}
          script: sh deploy.sh
          
  
